# SQLite DB
spring.datasource.url=jdbc:sqlite:nba_sportsbook.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

# Odds API (put your own key locally)
odds.api.key=YOUR_API_KEY_HERE